# replace place to define the default model covered by this document, first letter must be uppercase
# replace place to define the default path of endpoints in this document, first letter must be lowercase
# add missing endpoints
# N.B. : must then be added to the pom to generate the controller and its associated models

openapi: '3.0.0'
info:
  description: 'Place API'
  version: '0.0.1'
  title: 'OpenAPI Place'
tags:
  - name: Place
paths:
  /place:
    get:
      tags:
        - Place
      summary: 'all Places'
      operationId: findAll
      responses:
        '200':
           description: 'OK'
           content:
              application/json:
                schema:
                  type: array
                  items:
                      $ref: '#/components/schemas/PlaceOpenApiModel'
    post:
      tags:
        - Place
      summary: 'create new place'
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceOpenApiModel'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceOpenApiModel'
    put:
      tags:
        - Place
      summary: 'Update existing place'
      operationId: update
      requestBody:
        description: 'Update existing place'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceOpenApiModel'

      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceOpenApiModel'

        '404':
          description: 'NOT FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /place/{id}:
    get:
      tags:
        - Place
      summary: 'Specific Place'
      operationId: findOne
      parameters:
        - name: id
          in: path
          description: 'Find a Place by its id'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceOpenApiModel'
        '404':
          description: 'NOT FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Place
      summary: 'delete a place'
      operationId: delete
      parameters:
        - name: id
          in: path
          description: 'Find a place by its id'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: DELETED
        '404':
          description: 'NOT FOUND'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    'PlaceOpenApiModel':
      description: 'Object representing a currently accessible ressource'
      type: object
      required:
        - longitude
        - latitude
        - altitude
        - numero
        - salleId
      properties:
        id:
          type: integer
          format: int64
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        altitude:
          type: number
          format: double
        numero:
          type: integer
        salleId:
          type: integer
          format: int64

    Error:
      description: 'format message for error return HTTP'
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string






