-- dump database

-- Table: category
CREATE TABLE public.category (
                                 id bigint NOT NULL PRIMARY KEY,
                                 name character varying(75)
);

-- Table: ville
CREATE TABLE public.ville (
                              id bigint NOT NULL PRIMARY KEY,
                              name character varying(255),
                              longitude double precision,
                              latitude double precision,
                              altitude double precision
);

-- Table: cinema
CREATE TABLE public.cinema (
                               id bigint NOT NULL PRIMARY KEY,
                               name character varying(255),
                               longitude double precision,
                               latitude double precision,
                               altitude double precision,
                               adresse character varying(255),
                               nombreSalles int,
                               ville_id bigint REFERENCES public.ville(id)
);

-- Table: seance
CREATE TABLE public.seance (
                               id bigint NOT NULL PRIMARY KEY,
                               heureDebut timestamp without time zone
);

-- Table: film
CREATE TABLE public.film (
                             id bigint NOT NULL PRIMARY KEY,
                             titre character varying(255),
                             duree double precision,
                             realisateur character varying(255),
                             description text,
                             photo text,
                             dateSortie date,
                             category_id bigint REFERENCES public.category(id)
);

-- Table: salle
CREATE TABLE public.salle (
                              id bigint NOT NULL PRIMARY KEY,
                              name character varying(255),
                              nombrePlaces int,
                              cinema_id bigint REFERENCES public.cinema(id)
);

-- Table: filmProjection
CREATE TABLE public.filmProjection (
                                       id bigint NOT NULL PRIMARY KEY,
                                       dateProjection date,
                                       prix double precision,
                                       salle_id bigint REFERENCES public.salle(id),
                                       film_id bigint REFERENCES public.film(id),
                                       seance_id bigint REFERENCES public.seance(id)
);

-- Table: place
CREATE TABLE public.place (
                              id bigint NOT NULL PRIMARY KEY,
                              numero int,
                              longitude double precision,
                              latitude double precision,
                              altitude double precision,
                              salle_id bigint REFERENCES public.salle(id)
);

-- Table: ticket
CREATE TABLE public.ticket (
                               id bigint NOT NULL PRIMARY KEY,
                               nomClient character varying(75),
                               prix double precision,
                               codePayement int,
                               reservee boolean,
                               place_id bigint REFERENCES public.place(id),
                               filmProjection_id bigint REFERENCES public.filmProjection(id)
);

-- Sequences for autogenerated IDs
CREATE SEQUENCE public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.category ALTER COLUMN id SET DEFAULT nextval('public.category_id_seq');

-- Séquence pour la table ville
CREATE SEQUENCE public.ville_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.ville ALTER COLUMN id SET DEFAULT nextval('public.ville_id_seq');

-- Séquence pour la table cinema
CREATE SEQUENCE public.cinema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.cinema ALTER COLUMN id SET DEFAULT nextval('public.cinema_id_seq');

-- Séquence pour la table seance
CREATE SEQUENCE public.seance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.seance ALTER COLUMN id SET DEFAULT nextval('public.seance_id_seq');

-- Séquence pour la table film
CREATE SEQUENCE public.film_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.film ALTER COLUMN id SET DEFAULT nextval('public.film_id_seq');

-- Séquence pour la table salle
CREATE SEQUENCE public.salle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.salle ALTER COLUMN id SET DEFAULT nextval('public.salle_id_seq');

-- Séquence pour la table filmProjection
CREATE SEQUENCE public.filmProjection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.filmProjection ALTER COLUMN id SET DEFAULT nextval('public.filmProjection_id_seq');

-- Séquence pour la table place
CREATE SEQUENCE public.place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.place ALTER COLUMN id SET DEFAULT nextval('public.place_id_seq');

-- Séquence pour la table ticket
CREATE SEQUENCE public.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE public.ticket ALTER COLUMN id SET DEFAULT nextval('public.ticket_id_seq');

--- foreign keys ---

-- Pour la table Cinema et Ville
ALTER TABLE public.cinema ADD CONSTRAINT fk_cinema_ville FOREIGN KEY (ville_id) REFERENCES public.ville(id);

-- Pour la table Salle et Cinema
ALTER TABLE public.salle ADD CONSTRAINT fk_salle_cinema FOREIGN KEY (cinema_id) REFERENCES public.cinema(id);

-- Pour la table Film et Category
ALTER TABLE public.film ADD CONSTRAINT fk_film_category FOREIGN KEY (category_id) REFERENCES public.category(id);

-- Pour la table FilmProjection et Salle
ALTER TABLE public.filmProjection ADD CONSTRAINT fk_filmProjection_salle FOREIGN KEY (salle_id) REFERENCES public.salle(id);

-- Pour la table FilmProjection et Film
ALTER TABLE public.filmProjection ADD CONSTRAINT fk_filmProjection_film FOREIGN KEY (film_id) REFERENCES public.film(id);

-- Pour la table FilmProjection et Seance
ALTER TABLE public.filmProjection ADD CONSTRAINT fk_filmProjection_seance FOREIGN KEY (seance_id) REFERENCES public.seance(id);

-- Pour la table Place et Salle
ALTER TABLE public.place ADD CONSTRAINT fk_place_salle FOREIGN KEY (salle_id) REFERENCES public.salle(id);

-- Pour la table Ticket et Place
ALTER TABLE public.ticket ADD CONSTRAINT fk_ticket_place FOREIGN KEY (place_id) REFERENCES public.place(id);

-- Pour la table Ticket et FilmProjection
ALTER TABLE public.ticket ADD CONSTRAINT fk_ticket_filmProjection FOREIGN KEY (filmProjection_id) REFERENCES public.filmProjection(id);
